name: Java CI
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: openjdk8
    - name: Build with Gradle
      run: ./gradlew shadowJar
